// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTeBo4GLEIf4Za3FSvEfn8B3YwHreE4SU',
    appId: '1:31514911754:web:45ea1ea096f2d1223d6bf3',
    messagingSenderId: '31514911754',
    projectId: 'musicverse-academy',
    authDomain: 'musicverse-academy.firebaseapp.com',
    storageBucket: 'musicverse-academy.firebasestorage.app',
    measurementId: 'G-F7F9BM261L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOK6X_MatEXkWwrgDzAHl9carlWqjbbbc',
    appId: '1:31514911754:android:61538c75b51589d03d6bf3',
    messagingSenderId: '31514911754',
    projectId: 'musicverse-academy',
    storageBucket: 'musicverse-academy.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApdNQslFzEWBkU30bgeidOwyRSeMrF-m0',
    appId: '1:31514911754:ios:35212e58497ef4d13d6bf3',
    messagingSenderId: '31514911754',
    projectId: 'musicverse-academy',
    storageBucket: 'musicverse-academy.firebasestorage.app',
    iosBundleId: 'com.musicverse.musicverseAcademyAdmin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApdNQslFzEWBkU30bgeidOwyRSeMrF-m0',
    appId: '1:31514911754:ios:35212e58497ef4d13d6bf3',
    messagingSenderId: '31514911754',
    projectId: 'musicverse-academy',
    storageBucket: 'musicverse-academy.firebasestorage.app',
    iosBundleId: 'com.musicverse.musicverseAcademyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTeBo4GLEIf4Za3FSvEfn8B3YwHreE4SU',
    appId: '1:31514911754:web:dec93a72dddff7123d6bf3',
    messagingSenderId: '31514911754',
    projectId: 'musicverse-academy',
    authDomain: 'musicverse-academy.firebaseapp.com',
    storageBucket: 'musicverse-academy.firebasestorage.app',
    measurementId: 'G-H4LHMXNW9L',
  );
}
