// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLOEIdc5kFcCSs3GsISvPF0eHvWHiztw',
    appId: '1:269204650355:web:128985aeda3918bb13ad06',
    messagingSenderId: '269204650355',
    projectId: 'adminmusicverse',
    authDomain: 'adminmusicverse.firebaseapp.com',
    storageBucket: 'adminmusicverse.firebasestorage.app',
    measurementId: 'G-V6HG4GEH84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwFFsFn1VuWHNlO0WWOXufVVU6OYLFso',
    appId: '1:269204650355:android:2c5ef26d9bae7c1513ad06',
    messagingSenderId: '269204650355',
    projectId: 'adminmusicverse',
    storageBucket: 'adminmusicverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyTb3IysunYsRWWYr74OzFxPP5ATzP7R8',
    appId: '1:269204650355:ios:1772287643f889f813ad06',
    messagingSenderId: '269204650355',
    projectId: 'adminmusicverse',
    storageBucket: 'adminmusicverse.firebasestorage.app',
    iosBundleId: 'com.musicverse.musicverseAcademyAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyTb3IysunYsRWWYr74OzFxPP5ATzP7R8',
    appId: '1:269204650355:ios:1772287643f889f813ad06',
    messagingSenderId: '269204650355',
    projectId: 'adminmusicverse',
    storageBucket: 'adminmusicverse.firebasestorage.app',
    iosBundleId: 'com.musicverse.musicverseAcademyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDLOEIdc5kFcCSs3GsISvPF0eHvWHiztw',
    appId: '1:269204650355:web:5d7d0b89b362009113ad06',
    messagingSenderId: '269204650355',
    projectId: 'adminmusicverse',
    authDomain: 'adminmusicverse.firebaseapp.com',
    storageBucket: 'adminmusicverse.firebasestorage.app',
    measurementId: 'G-6FVZ4PFX7V',
  );
}
